##############################
#SETTINGS FILE FOR PROJECT01#
##############################

# if the exlusion is for all users enter in this list
# formatting for excluding a file is /path/to/exclused/file
# formatting for excluding a directory is /path/to/exclused/directory/

# Settings to better control how much and what is backed up
[settings]
  Use_Exclusions = true
  Use_Inclusions = false

# These are for lists of files/directories that should not be backed up
[exclusions]
  # Standard Exlusions made with every product can be changed if need be.
  Default_Exclusions = [

  ]
  # General Exclusions is for files/directories that should be excluded for all users
  General_Exclusions = [
    "My Music",
    "My Pictures",
    "My Videos",
    "NTUSER.DAT",
    "ntuser.dat.LOG1",
    "ntuser.dat.LOG2",
    "AppData",
    "Appdata",
    "Dropbox (Liberty University)"
    ]

  Profile_Exclusions = [

  ]

# These are for lists of files/directories that should be backed up
[inclusions]
# Standard Inclusions made with every product can be changed if need be.
  Default_Inclusions = [

  ]
  # General Inclusions is for files/directories that should be included for all users
  General_Inclusions = [
    "AppData\\Local\\Google\\Chrome\\User Data\\Default\\Bookmarks"
    ]

  Profile_Inclusions = [

    ]

[advanced_settings]
  Use_Ecryption = false
  Domain = "Company Domain here"
